add doc github actions

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -5,6 +5,7 @@ HOST ?= 127.0.0.1
 PORT ?= 8000
 
 MKDOCS = uv run mkdocs
+MIKE = uv run mike
 
 # Generate mkdocs.yml file from API reference documentation
 gen-mkdocs-yml:
@@ -16,11 +17,26 @@ build-doc:
 	@make gen-mkdocs-yml
 	$(MKDOCS) build
 
+require-version:
+	@if [ -z "$(VERSION)" ]; then \
+		echo "ERROR: VERSION is required. Usage: make build-doc-version VERSION=1.2.3"; \
+		exit 1; \
+	fi
+
+build-doc-version: require-version
+	$(MIKE) deploy --push --update-aliases $(VERSION) latest
+	$(MIKE) set-default --push latest
+
+# Delete a deployed docs version
+delete-doc-version: require-version
+	@make gen-mkdocs-yml
+	$(MIKE) delete --push $(VERSION)
+
 # Start development server
 serve-doc:
 	@uv sync
 	@make gen-mkdocs-yml
-	$(MKDOCS) serve -a $(HOST):$(PORT)
+	$(MIKE) serve -a $(HOST):$(PORT)
 
 # Clean build artifacts
 clean:
